global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'spring-boot-microservices'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
        - 'host.docker.internal:30081' # Buku
        - 'host.docker.internal:30082' # Anggota
        - 'host.docker.internal:30083' # Peminjaman
        - 'host.docker.internal:30084' # Pengembalian
        - 'host.docker.internal:30000' # Gateway